### ISSUE TITLE
Find palindrome

### ISSUE THREAD

**Issue by wINTerpEArdEli** [yd-personal-practice/personal-practice#1]
## Abstract

입력된 단어가 palindrome 배열을 가진 단어인지 구분한다.

월요일 != 일요월
일요일 == 일요일
토마토 == 토마토

## Task

- [x]  단어를 입력 받는다
- [x]  입력 받은 단어를 뒤집는다
- [x]  입력한 단어와 뒤집은 단어가 같은지 확인한다

## Referance

[palindrome](https://ko.wikipedia.org/wiki/%ED%9A%8C%EB%AC%B8)
[algorithem](https://velog.io/@situm26/%EC%95%8C%EA%B3%A0%EB%A6%AC%EC%A6%98-%ED%8C%94%EB%A6%B0%EB%93%9C%EB%A1%AC-%EB%AC%B8%EC%A0%9C)
